{% set name = "unifuncnet" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PedroMTQ/UniFuncNet/archive/refs/tags/{{ version }}.tar.gz
  sha256: 90c6ea0c63b559f0441d052a1f17e7d03eec8025d48e7b8c009e2d3072a51676

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - unifuncnet=unifuncnet.__main__:main

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=42
    - wheel
  run:
    - beautifulsoup4
    - lxml
    - python >=3.9
    - requests

test:
  imports:
    - unifuncnet
  commands:
    - pip check
    - unifuncnet --help
  requires:
    - pip

about:
  home: https://github.com/PedroMTQ/UniFuncNet
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Biological network annotation tool.
  description: |
    UniFuncNet is network annotation tool that integrates multiple biological 
    databases into one composite output.
  dev_url: https://github.com/PedroMTQ/UniFuncNet

extra:
  recipe-maintainers:
    - PedroMTQ
